fixtures:
  symlinks:
    beegfs: "#{source_dir}"
  forge_modules:
     stdlib: "puppetlabs/stdlib"
     concat: "puppetlabs/concat"
     apt: "puppetlabs/apt"
     yumrepo_core: "puppetlabs/yumrepo_core"
