fixtures:
  symlinks:
    beegfs: "#{source_dir}"
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
      ref: 7.1.0
    concat: "puppetlabs/concat"
    apt:
      repo: puppetlabs/apt
      ref: 8.4.1
    yumrepo_core: "puppetlabs/yumrepo_core"
